### ISSUE TITLE
Can't log in - getting "Error connecting to server!" error

### ISSUE THREAD

**Issue by patbeagan1** [Saveyour-Team/Saveyour#31]

**Comment by NateFuller** [comment]
Looking into this immediately, we're experiencing the same issue on our end. The server appears to be refusing connections. @bpteich will be taking this.

**Comment by bpteich** [comment]
Restarted the server, connections are now working as normal.  The bug appears to be the memory leak though was slowing the program before. We found a possible source for it and are fixing it at the moment, but since it takes about a week to harm the server they should be okay in the meantime.

Closing this issue and opening one for the memory leak.
